/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

#include "AbstractSolution.h"

class p2 : public AbstractSolution {
private:
	constexpr const static unsigned int _MAX_ = 4000000;
public:
	virtual void solve();
};